kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: muting
  labels:
    app: muting
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: muting.example.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: muting
            port:
              number: 443
